### ISSUE TITLE
Fast Extraction Method

### ISSUE THREAD

**Issue by leaf918** [nibtehaz/PPG2ABP#12]
FROM
`        for i in tqdm(range(len(f[ky])), desc='Reading Records'):  # reading the records

            signal = []  # ppg signal
            bp = []  # abp signal

            output_str = '10s,SBP,DBP\n'  # starting text for a new csv file

            for j in tqdm(range(len(f[f[ky][i][0]])),
                          desc='Reading Samples from Record {}/3000'.format(i + 1)):  # reading samples from records

                signal.append(f[f[ky][i][0]][j][0])  # ppg signal
                bp.append(f[f[ky][i][0]][j][1])  # abp signal`
TO
 
`dir_output='processed_data'
for mat_path in glob("data_uci/*.mat"):
    table_name=(os.path.basename(mat_path).replace(".mat",''))
    print(table_name)

    with h5py.File(mat_path, 'r') as f:
        for i in tqdm(range(len(f[table_name])), desc='Reading Records'):  # reading the records
            des_ref = f[table_name][i][0]  # 3000 records
            list_hdf5record = f[des_ref][[*range(len(f[des_ref]))]]
            df_raw = pd.DataFrame(list_hdf5record, columns=['PPG', 'ABP', 'X'])
            df_raw.to_csv(os.path.join(dir_output,'%s_record_%s.csv')%(os.path.basename(mat_path),i))
`
This can boost the speed of extraction.

**Comment by nibtehaz** [comment]
Thank you for your suggestion, I appreciate it. Currently, this project isn't active anymore.

**Comment by leaf918** [comment]
Thanks.
