### ISSUE TITLE
How can we give raw PPG signal as input to your code?

### ISSUE THREAD

**Issue by nagapavan525** [nibtehaz/PPG2ABP#2]
Hi Nabil Ibtehaz,

I went through your paper, it's really cool.

I have a query for you that how can a raw PPG signal be given as input to your evaluate/predict code as you used already processed code by someone?

Does it work if a raw PPG signal is given as input or it needs to be preprocessed PPG as input? If it does not work with raw signals, what are the preprocessing steps need to perform on the raw signal to give as input to evaluate?

Thanks in advance,
NPK

**Comment by nibtehaz** [comment]
Hi @nagapavan525, sorry for the delayed response. Thank you for your interest in our project.

The models and the overall pipeline relies on the preprocessing of the PPG signal. The preprocessing steps are well described in the paper https://ieeexplore.ieee.org/document/7491263 ,whose data source we used.

It should not be impossible to work the model on raw data. You may perhaps try applying transfer learning, but we should be careful about signal properties like sampling rate and the acquisition mechanism.

Hope this helps. Thank you.

**Comment by nagapavan525** [comment]
Hi @nibtehaz,

Agree that we need to follow strict pre-processing for the raw signals by keeping the sampling rate in mind (as can see mimic II ppg signals are with a sampling rate of 125 Hz but real-time varies w.r.to the device we use and environment).

Thanks for your inputs.
