### ISSUE TITLE
max and min?

### ISSUE THREAD

**Issue by mfrimannm** [nibtehaz/PPG2ABP#5]
So given a new set of data where you do not know the ground truth and therefore cant have a meta file with max and min values for the ABP signal, what can you then do?

https://github.com/nibtehaz/PPG2ABP/blob/6109d4d0c213655486a17dd25900675b746beabd/codes/evaluate.py#L55

**Comment by nibtehaz** [comment]
Hi @mfrimannm  . Thank you for your interest in our project.

If it is like that the PPG signals are of similar quality and are from the same data distribution then you can use the same max_abp min_abp values. However, if they aren't, then you need to do some transfer learning, for that you'd need the abp signals.

This is just for the sake of normalization, so you understand if depends completely on the data.

Hope this helps.
