### ISSUE TITLE
Preprocessing from Kachuee's paper

### ISSUE THREAD

**Issue by tonyKxm** [nibtehaz/PPG2ABP#6]
Hi!

I downloaded the dataset from UCI repository but I found the dataset was not using wavelet decomposition( Kachuee's 2017 paper) as you mentioned in your PPG2ABP paper, actually,it was using Kachuee's 2015 preprocessing method. Do you have Kachuee's 2017 dataset?

Thanks!

**Comment by nibtehaz** [comment]
Hi Tomy, sorry I missed this issue. Unfortunately I don't have that dataset. I only worked with the dataset they made available online.
